# Generated by Django 6.0.7 on 2026-07-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Farm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="nombre")),
                ("code", models.SlugField(max_length=30, unique=True, verbose_name="código")),
                ("municipality", models.CharField(max_length=100, verbose_name="municipio")),
                ("province", models.CharField(max_length=100, verbose_name="provincia")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="alta en el sistema"),
                ),
            ],
            options={
                "verbose_name": "granja",
                "verbose_name_plural": "granjas",
                "ordering": ["name"],
            },
        ),
    ]
