# Generated by Django 6.0.7 on 2026-07-21 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("farms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Animal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("ear_tag", models.CharField(max_length=20, verbose_name="crotal")),
                ("birth_date", models.DateField(verbose_name="fecha de nacimiento")),
                (
                    "breed",
                    models.CharField(
                        choices=[
                            ("holstein", "Frisona"),
                            ("jersey", "Jersey"),
                            ("procross", "Procross"),
                            ("brown_swiss", "Parda Alpina"),
                            ("other", "Otra"),
                        ],
                        default="holstein",
                        max_length=11,
                        verbose_name="raza",
                    ),
                ),
                (
                    "lactation_number",
                    models.PositiveSmallIntegerField(default=0, verbose_name="número de lactación"),
                ),
                (
                    "last_calving_date",
                    models.DateField(blank=True, null=True, verbose_name="último parto"),
                ),
                (
                    "culled_date",
                    models.DateField(blank=True, null=True, verbose_name="fecha de baja"),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="animals",
                        to="farms.farm",
                        verbose_name="granja",
                    ),
                ),
            ],
            options={
                "verbose_name": "animal",
                "verbose_name_plural": "animales",
                "ordering": ["farm", "ear_tag"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("farm", "ear_tag"), name="farms_animal_unique_farm_ear_tag"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("culled_date__isnull", True),
                            ("culled_date__gte", models.F("birth_date")),
                            _connector="OR",
                        ),
                        name="farms_animal_culled_after_birth",
                    ),
                ],
            },
        ),
    ]
