# Generated by Django 6.0.7 on 2026-07-21 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("farms", "0002_animal"),
    ]

    operations = [
        migrations.CreateModel(
            name="Milking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField(verbose_name="fecha")),
                (
                    "liters",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True, verbose_name="litros"
                    ),
                ),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milkings",
                        to="farms.animal",
                        verbose_name="animal",
                    ),
                ),
            ],
            options={
                "verbose_name": "ordeño",
                "verbose_name_plural": "ordeños",
                "ordering": ["-date", "animal"],
                "indexes": [models.Index(fields=["date"], name="farms_milking_date_idx")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("animal", "date"), name="farms_milking_unique_animal_date"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("liters__isnull", True), ("liters__gte", 0), _connector="OR"
                        ),
                        name="farms_milking_liters_not_negative",
                    ),
                ],
            },
        ),
    ]
