# Generated by Django 6.0.7 on 2026-07-21 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("farms", "0003_milking"),
    ]

    operations = [
        migrations.CreateModel(
            name="MilkRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField(verbose_name="fecha del control")),
                (
                    "fat_pct",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=4,
                        null=True,
                        verbose_name="grasa (%)",
                    ),
                ),
                (
                    "protein_pct",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=4,
                        null=True,
                        verbose_name="proteína (%)",
                    ),
                ),
                (
                    "somatic_cell_count",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="células somáticas (células/ml)"
                    ),
                ),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milk_records",
                        to="farms.animal",
                        verbose_name="animal",
                    ),
                ),
            ],
            options={
                "verbose_name": "control lechero",
                "verbose_name_plural": "controles lecheros",
                "ordering": ["-date", "animal"],
                "indexes": [models.Index(fields=["date"], name="farms_milkrecord_date_idx")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("animal", "date"), name="farms_milkrecord_unique_animal_date"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("fat_pct__isnull", True), ("fat_pct__gte", 0), _connector="OR"
                        ),
                        name="farms_milkrecord_fat_pct_not_negative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("protein_pct__isnull", True), ("protein_pct__gte", 0), _connector="OR"
                        ),
                        name="farms_milkrecord_protein_pct_not_negative",
                    ),
                ],
            },
        ),
    ]
