# Generated by Django 6.0.7 on 2026-07-31 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("farms", "0004_milkrecord"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Milking",
            new_name="DailyYield",
        ),
        migrations.AlterModelOptions(
            name="dailyyield",
            options={
                "ordering": ["-date", "animal"],
                "verbose_name": "producción diaria",
                "verbose_name_plural": "producciones diarias",
            },
        ),
        migrations.AlterModelOptions(
            name="milkrecord",
            options={
                "ordering": ["-date", "animal"],
                "verbose_name": "control lechero individual",
                "verbose_name_plural": "controles lecheros individuales",
            },
        ),
        migrations.RemoveConstraint(
            model_name="dailyyield",
            name="farms_milking_unique_animal_date",
        ),
        migrations.RemoveConstraint(
            model_name="dailyyield",
            name="farms_milking_liters_not_negative",
        ),
        migrations.RenameIndex(
            model_name="dailyyield",
            new_name="farms_dailyyield_date_idx",
            old_name="farms_milking_date_idx",
        ),
        migrations.AddConstraint(
            model_name="dailyyield",
            constraint=models.UniqueConstraint(
                fields=("animal", "date"), name="farms_dailyyield_unique_animal_date"
            ),
        ),
        migrations.AddConstraint(
            model_name="dailyyield",
            constraint=models.CheckConstraint(
                condition=models.Q(("liters__isnull", True), ("liters__gte", 0), _connector="OR"),
                name="farms_dailyyield_liters_not_negative",
            ),
        ),
    ]
