# Generated by Django 6.0.7 on 2026-07-31 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("farms", "0005_rename_milking_dailyyield_alter_dailyyield_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyyield",
            name="animal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="daily_yields",
                to="farms.animal",
                verbose_name="animal",
            ),
        ),
    ]
