# Generated by Django 6.0.7 on 2026-08-04 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("farms", "0006_alter_dailyyield_animal"),
    ]

    operations = [
        migrations.CreateModel(
            name="RawMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True, verbose_name="nombre")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("concentrate", "Concentrado"),
                            ("forage", "Forraje"),
                            ("byproduct", "Subproducto"),
                            ("mineral", "Corrector mineral-vitamínico"),
                            ("other", "Otra"),
                        ],
                        max_length=11,
                        verbose_name="categoría",
                    ),
                ),
            ],
            options={
                "verbose_name": "materia prima",
                "verbose_name_plural": "materias primas",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="Plot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="nombre")),
                ("code", models.CharField(max_length=40, verbose_name="código")),
                (
                    "area_ha",
                    models.DecimalField(
                        decimal_places=4, max_digits=7, verbose_name="superficie (ha)"
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plots",
                        to="farms.farm",
                        verbose_name="granja",
                    ),
                ),
            ],
            options={
                "verbose_name": "parcela",
                "verbose_name_plural": "parcelas",
                "ordering": ["farm", "name"],
            },
        ),
        migrations.CreateModel(
            name="Crop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "species",
                    models.CharField(
                        choices=[
                            ("maize", "Maíz forrajero"),
                            ("italian_ryegrass", "Raigrás italiano"),
                            ("grass_mix", "Pradera polifita"),
                            ("other", "Otra"),
                        ],
                        max_length=16,
                        verbose_name="especie",
                    ),
                ),
                ("season", models.PositiveSmallIntegerField(verbose_name="campaña")),
                ("sowing_date", models.DateField(blank=True, null=True, verbose_name="siembra")),
                ("harvest_date", models.DateField(blank=True, null=True, verbose_name="cosecha")),
                (
                    "plot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crops",
                        to="farms.plot",
                        verbose_name="parcela",
                    ),
                ),
            ],
            options={
                "verbose_name": "cultivo",
                "verbose_name_plural": "cultivos",
                "ordering": ["-season", "plot"],
            },
        ),
        migrations.CreateModel(
            name="Silage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(max_length=40, verbose_name="código del silo")),
                ("sealed_date", models.DateField(blank=True, null=True, verbose_name="cierre")),
                ("opened_date", models.DateField(blank=True, null=True, verbose_name="apertura")),
                (
                    "crop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="silages",
                        to="farms.crop",
                        verbose_name="cultivo",
                    ),
                ),
            ],
            options={
                "verbose_name": "ensilado",
                "verbose_name_plural": "ensilados",
                "ordering": ["-sealed_date", "code"],
            },
        ),
        migrations.CreateModel(
            name="NIRAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField(verbose_name="fecha del análisis")),
                (
                    "laboratory",
                    models.CharField(blank=True, max_length=120, verbose_name="laboratorio"),
                ),
                (
                    "silage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nir_analyses",
                        to="farms.silage",
                        verbose_name="ensilado",
                    ),
                ),
            ],
            options={
                "verbose_name": "análisis NIR",
                "verbose_name_plural": "análisis NIR",
                "ordering": ["-date", "silage"],
            },
        ),
        migrations.AddConstraint(
            model_name="plot",
            constraint=models.UniqueConstraint(
                fields=("farm", "code"), name="farms_plot_unique_farm_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="plot",
            constraint=models.CheckConstraint(
                condition=models.Q(("area_ha__gt", 0)), name="farms_plot_area_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="crop",
            constraint=models.UniqueConstraint(
                fields=("plot", "season", "species"), name="farms_crop_unique_plot_season_species"
            ),
        ),
        migrations.AddConstraint(
            model_name="crop",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("sowing_date__isnull", True),
                    ("harvest_date__isnull", True),
                    ("harvest_date__gte", models.F("sowing_date")),
                    _connector="OR",
                ),
                name="farms_crop_harvest_after_sowing",
            ),
        ),
        migrations.AddConstraint(
            model_name="silage",
            constraint=models.UniqueConstraint(
                fields=("crop", "code"), name="farms_silage_unique_crop_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="silage",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("sealed_date__isnull", True),
                    ("opened_date__isnull", True),
                    ("opened_date__gte", models.F("sealed_date")),
                    _connector="OR",
                ),
                name="farms_silage_opened_after_sealed",
            ),
        ),
        migrations.AddIndex(
            model_name="niranalysis",
            index=models.Index(fields=["date"], name="farms_niranalysis_date_idx"),
        ),
        migrations.AddConstraint(
            model_name="niranalysis",
            constraint=models.UniqueConstraint(
                fields=("silage", "date"), name="farms_niranalysis_unique_silage_date"
            ),
        ),
    ]
