# Generated by Django 6.0.7 on 2026-08-04 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("farms", "0007_rawmaterial_plot_crop_silage_niranalysis_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnimalBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="nombre")),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batches",
                        to="farms.farm",
                        verbose_name="granja",
                    ),
                ),
            ],
            options={
                "verbose_name": "lote de animales",
                "verbose_name_plural": "lotes de animales",
                "ordering": ["farm", "name"],
            },
        ),
        migrations.CreateModel(
            name="AnimalBatchMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date_from", models.DateField(verbose_name="desde")),
                ("date_to", models.DateField(blank=True, null=True, verbose_name="hasta")),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batch_memberships",
                        to="farms.animal",
                        verbose_name="animal",
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="farms.animalbatch",
                        verbose_name="lote",
                    ),
                ),
            ],
            options={
                "verbose_name": "pertenencia a lote",
                "verbose_name_plural": "pertenencias a lote",
                "ordering": ["-date_from", "animal"],
            },
        ),
        migrations.CreateModel(
            name="Ration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="nombre")),
                ("formulated_on", models.DateField(verbose_name="fecha de formulación")),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rations",
                        to="farms.farm",
                        verbose_name="granja",
                    ),
                ),
            ],
            options={
                "verbose_name": "ración",
                "verbose_name_plural": "raciones",
                "ordering": ["farm", "name", "-formulated_on"],
            },
        ),
        migrations.CreateModel(
            name="BatchRation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date_from", models.DateField(verbose_name="desde")),
                ("date_to", models.DateField(blank=True, null=True, verbose_name="hasta")),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ration_periods",
                        to="farms.animalbatch",
                        verbose_name="lote",
                    ),
                ),
                (
                    "ration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="batch_periods",
                        to="farms.ration",
                        verbose_name="ración",
                    ),
                ),
            ],
            options={
                "verbose_name": "ración del lote",
                "verbose_name_plural": "raciones del lote",
                "ordering": ["-date_from", "batch"],
            },
        ),
        migrations.CreateModel(
            name="RationIngredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "dry_matter_kg",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="kg de materia seca por animal y día",
                    ),
                ),
                (
                    "ration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingredients",
                        to="farms.ration",
                        verbose_name="ración",
                    ),
                ),
                (
                    "raw_material",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ration_ingredients",
                        to="farms.rawmaterial",
                        verbose_name="materia prima",
                    ),
                ),
                (
                    "silage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ration_ingredients",
                        to="farms.silage",
                        verbose_name="ensilado propio",
                    ),
                ),
            ],
            options={
                "verbose_name": "ingrediente de la ración",
                "verbose_name_plural": "ingredientes de la ración",
                "ordering": ["ration", "-dry_matter_kg"],
            },
        ),
        migrations.AddConstraint(
            model_name="animalbatch",
            constraint=models.UniqueConstraint(
                fields=("farm", "name"), name="farms_animalbatch_unique_farm_name"
            ),
        ),
        migrations.AddIndex(
            model_name="animalbatchmembership",
            index=models.Index(fields=["date_from"], name="farms_abmembership_from_idx"),
        ),
        migrations.AddConstraint(
            model_name="animalbatchmembership",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("date_to__isnull", True),
                    ("date_to__gte", models.F("date_from")),
                    _connector="OR",
                ),
                name="farms_animalbatchmembership_end_after_start",
            ),
        ),
        migrations.AddConstraint(
            model_name="animalbatchmembership",
            constraint=models.UniqueConstraint(
                condition=models.Q(("date_to__isnull", True)),
                fields=("animal",),
                name="farms_animalbatchmembership_one_open_per_animal",
            ),
        ),
        migrations.AddConstraint(
            model_name="ration",
            constraint=models.UniqueConstraint(
                fields=("farm", "name", "formulated_on"),
                name="farms_ration_unique_farm_name_formulated_on",
            ),
        ),
        migrations.AddIndex(
            model_name="batchration",
            index=models.Index(fields=["date_from"], name="farms_batchration_from_idx"),
        ),
        migrations.AddConstraint(
            model_name="batchration",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("date_to__isnull", True),
                    ("date_to__gte", models.F("date_from")),
                    _connector="OR",
                ),
                name="farms_batchration_end_after_start",
            ),
        ),
        migrations.AddConstraint(
            model_name="batchration",
            constraint=models.UniqueConstraint(
                condition=models.Q(("date_to__isnull", True)),
                fields=("batch",),
                name="farms_batchration_one_open_per_batch",
            ),
        ),
        migrations.AddConstraint(
            model_name="rationingredient",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("raw_material__isnull", False), ("silage__isnull", True)),
                    models.Q(("raw_material__isnull", True), ("silage__isnull", False)),
                    _connector="OR",
                ),
                name="farms_rationingredient_exactly_one_source",
            ),
        ),
        migrations.AddConstraint(
            model_name="rationingredient",
            constraint=models.CheckConstraint(
                condition=models.Q(("dry_matter_kg__gt", 0)),
                name="farms_rationingredient_dry_matter_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="rationingredient",
            constraint=models.UniqueConstraint(
                fields=("ration", "silage"), name="farms_rationingredient_unique_ration_silage"
            ),
        ),
        migrations.AddConstraint(
            model_name="rationingredient",
            constraint=models.UniqueConstraint(
                fields=("ration", "raw_material"),
                name="farms_rationingredient_unique_ration_raw_material",
            ),
        ),
    ]
