# Generated by Django 6.0.7 on 2026-08-04 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("farms", "0008_animalbatch_animalbatchmembership_ration_batchration_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Analyte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.SlugField(max_length=40, unique=True, verbose_name="código")),
                ("name", models.CharField(max_length=120, verbose_name="nombre")),
                ("unit", models.CharField(max_length=20, verbose_name="unidad")),
            ],
            options={
                "verbose_name": "analito",
                "verbose_name_plural": "analitos",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TargetProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.SlugField(max_length=40, unique=True, verbose_name="código")),
                ("name", models.CharField(max_length=120, verbose_name="nombre")),
                ("description", models.TextField(blank=True, verbose_name="descripción")),
            ],
            options={
                "verbose_name": "perfil de destino",
                "verbose_name_plural": "perfiles de destino",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BatchMilkSample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField(verbose_name="fecha de la muestra")),
                (
                    "laboratory",
                    models.CharField(blank=True, max_length=120, verbose_name="laboratorio"),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milk_samples",
                        to="farms.animalbatch",
                        verbose_name="lote",
                    ),
                ),
            ],
            options={
                "verbose_name": "muestra de leche del lote",
                "verbose_name_plural": "muestras de leche del lote",
                "ordering": ["-date", "batch"],
            },
        ),
        migrations.CreateModel(
            name="AnalysisResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "value",
                    models.DecimalField(decimal_places=4, max_digits=12, verbose_name="valor"),
                ),
                (
                    "nir_analysis",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="farms.niranalysis",
                        verbose_name="análisis NIR",
                    ),
                ),
                (
                    "analyte",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="results",
                        to="farms.analyte",
                        verbose_name="analito",
                    ),
                ),
                (
                    "milk_sample",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="farms.batchmilksample",
                        verbose_name="muestra de leche",
                    ),
                ),
            ],
            options={
                "verbose_name": "resultado analítico",
                "verbose_name_plural": "resultados analíticos",
                "ordering": ["analyte"],
            },
        ),
        migrations.CreateModel(
            name="TargetRange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "min_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=12,
                        null=True,
                        verbose_name="mínimo",
                    ),
                ),
                (
                    "max_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=12,
                        null=True,
                        verbose_name="máximo",
                    ),
                ),
                (
                    "analyte",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="target_ranges",
                        to="farms.analyte",
                        verbose_name="analito",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ranges",
                        to="farms.targetprofile",
                        verbose_name="perfil de destino",
                    ),
                ),
            ],
            options={
                "verbose_name": "rango objetivo",
                "verbose_name_plural": "rangos objetivo",
                "ordering": ["profile", "analyte"],
            },
        ),
        migrations.AddIndex(
            model_name="batchmilksample",
            index=models.Index(fields=["date"], name="farms_batchmilksample_date_idx"),
        ),
        migrations.AddConstraint(
            model_name="batchmilksample",
            constraint=models.UniqueConstraint(
                fields=("batch", "date"), name="farms_batchmilksample_unique_batch_date"
            ),
        ),
        migrations.AddConstraint(
            model_name="analysisresult",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("milk_sample__isnull", False), ("nir_analysis__isnull", True)),
                    models.Q(("milk_sample__isnull", True), ("nir_analysis__isnull", False)),
                    _connector="OR",
                ),
                name="farms_analysisresult_exactly_one_sample",
            ),
        ),
        migrations.AddConstraint(
            model_name="analysisresult",
            constraint=models.UniqueConstraint(
                fields=("nir_analysis", "analyte"), name="farms_analysisresult_unique_nir_analyte"
            ),
        ),
        migrations.AddConstraint(
            model_name="analysisresult",
            constraint=models.UniqueConstraint(
                fields=("milk_sample", "analyte"), name="farms_analysisresult_unique_sample_analyte"
            ),
        ),
        migrations.AddConstraint(
            model_name="targetrange",
            constraint=models.UniqueConstraint(
                fields=("profile", "analyte"), name="farms_targetrange_unique_profile_analyte"
            ),
        ),
        migrations.AddConstraint(
            model_name="targetrange",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("min_value__isnull", False), ("max_value__isnull", False), _connector="OR"
                ),
                name="farms_targetrange_at_least_one_bound",
            ),
        ),
        migrations.AddConstraint(
            model_name="targetrange",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("min_value__isnull", True),
                    ("max_value__isnull", True),
                    ("max_value__gte", models.F("min_value")),
                    _connector="OR",
                ),
                name="farms_targetrange_max_above_min",
            ),
        ),
    ]
