# Generated by Django 6.0.7 on 2026-08-10 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("farms", "0009_analyte_targetprofile_batchmilksample_analysisresult_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="IngestionRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("milking_robot", "Robot o sala de ordeño"),
                            ("milk_recording", "Núcleo de control lechero"),
                            ("nir_lab", "Laboratorio de análisis NIR"),
                            ("field_notebook", "Cuaderno de campo"),
                        ],
                        max_length=20,
                        verbose_name="fuente",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="referencia de origen"
                    ),
                ),
                (
                    "ingested_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="fecha de ingesta"),
                ),
                (
                    "records_loaded",
                    models.PositiveIntegerField(default=0, verbose_name="registros cargados"),
                ),
                (
                    "records_rejected",
                    models.PositiveIntegerField(default=0, verbose_name="registros rechazados"),
                ),
            ],
            options={
                "verbose_name": "carga de datos",
                "verbose_name_plural": "cargas de datos",
                "ordering": ["-ingested_at"],
                "indexes": [
                    models.Index(
                        fields=["source", "ingested_at"], name="farms_ingestionrun_src_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="IngestionReject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("line_number", models.PositiveIntegerField(verbose_name="línea")),
                ("raw", models.TextField(verbose_name="contenido original")),
                ("reason", models.CharField(max_length=200, verbose_name="motivo")),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rejects",
                        to="farms.ingestionrun",
                        verbose_name="carga",
                    ),
                ),
            ],
            options={
                "verbose_name": "registro rechazado",
                "verbose_name_plural": "registros rechazados",
                "ordering": ["run", "line_number"],
            },
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="ingestion_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="farms.ingestionrun",
                verbose_name="carga de origen",
            ),
        ),
        migrations.AddField(
            model_name="animal",
            name="ingestion_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="farms.ingestionrun",
                verbose_name="carga de origen",
            ),
        ),
        migrations.AddField(
            model_name="animalbatch",
            name="ingestion_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="farms.ingestionrun",
                verbose_name="carga de origen",
            ),
        ),
        migrations.AddField(
            model_name="animalbatchmembership",
            name="ingestion_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="farms.ingestionrun",
                verbose_name="carga de origen",
            ),
        ),
        migrations.AddField(
            model_name="batchmilksample",
            name="ingestion_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="farms.ingestionrun",
                verbose_name="carga de origen",
            ),
        ),
        migrations.AddField(
            model_name="batchration",
            name="ingestion_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="farms.ingestionrun",
                verbose_name="carga de origen",
            ),
        ),
        migrations.AddField(
            model_name="crop",
            name="ingestion_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="farms.ingestionrun",
                verbose_name="carga de origen",
            ),
        ),
        migrations.AddField(
            model_name="dailyyield",
            name="ingestion_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="farms.ingestionrun",
                verbose_name="carga de origen",
            ),
        ),
        migrations.AddField(
            model_name="farm",
            name="ingestion_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="farms.ingestionrun",
                verbose_name="carga de origen",
            ),
        ),
        migrations.AddField(
            model_name="milkrecord",
            name="ingestion_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="farms.ingestionrun",
                verbose_name="carga de origen",
            ),
        ),
        migrations.AddField(
            model_name="niranalysis",
            name="ingestion_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="farms.ingestionrun",
                verbose_name="carga de origen",
            ),
        ),
        migrations.AddField(
            model_name="plot",
            name="ingestion_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="farms.ingestionrun",
                verbose_name="carga de origen",
            ),
        ),
        migrations.AddField(
            model_name="ration",
            name="ingestion_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="farms.ingestionrun",
                verbose_name="carga de origen",
            ),
        ),
        migrations.AddField(
            model_name="rationingredient",
            name="ingestion_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="farms.ingestionrun",
                verbose_name="carga de origen",
            ),
        ),
        migrations.AddField(
            model_name="silage",
            name="ingestion_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="farms.ingestionrun",
                verbose_name="carga de origen",
            ),
        ),
    ]
