# Generated by Django 6.0.7 on 2026-08-11 12:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("farms", "0010_ingestionrun_ingestionreject_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingestionrun",
            name="source",
            field=models.CharField(
                choices=[
                    ("milking_robot", "Robot o sala de ordeño"),
                    ("milk_recording", "Núcleo de control lechero"),
                    ("nir_lab", "Laboratorio de análisis NIR"),
                    ("milk_lab", "Laboratorio de análisis de leche"),
                    ("field_notebook", "Cuaderno de campo"),
                ],
                max_length=20,
                verbose_name="fuente",
            ),
        ),
    ]
